// Généré par `ios/Tools/make-customisation-preview-manifest.py` depuis
// `assets/illustrations/aperçu personnalisation/`. Ne pas éditer à la main :
// relancer le script quand le dossier change.

extension BookCustomisationPreview {
    /// Les 200 aperçus du dossier, image de repli exclue — chacun
    /// écrit comme sur le disque.
    public static let availableFileNames: Set<String> = [
        "Pointillés=off, Ratio image=0%, Fun fact=off, Stickers=0, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=0%, Fun fact=off, Stickers=0, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=0%, Fun fact=off, Stickers=0, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=0%, Fun fact=off, Stickers=1, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=0%, Fun fact=off, Stickers=1, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=0%, Fun fact=off, Stickers=1, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=0%, Fun fact=off, Stickers=2, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=0%, Fun fact=off, Stickers=2, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=0%, Fun fact=off, Stickers=2, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=0%, Fun fact=off, Stickers=3, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=0%, Fun fact=off, Stickers=3, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=0%, Fun fact=off, Stickers=3, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=0%, Fun fact=off, Stickers=4, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=0%, Fun fact=off, Stickers=4, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=0%, Fun fact=off, Stickers=4, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=0%, Fun fact=on, Stickers=0, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=0%, Fun fact=on, Stickers=0, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=0%, Fun fact=on, Stickers=0, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=0%, Fun fact=on, Stickers=1, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=0%, Fun fact=on, Stickers=1, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=0%, Fun fact=on, Stickers=1, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=0%, Fun fact=on, Stickers=2, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=0%, Fun fact=on, Stickers=2, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=0%, Fun fact=on, Stickers=2, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=0%, Fun fact=on, Stickers=3, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=0%, Fun fact=on, Stickers=3, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=0%, Fun fact=on, Stickers=3, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=0%, Fun fact=on, Stickers=4, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=0%, Fun fact=on, Stickers=4, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=0%, Fun fact=on, Stickers=4, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=100%, Fun fact=off, Stickers=0, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=100%, Fun fact=off, Stickers=0, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=100%, Fun fact=off, Stickers=0, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=100%, Fun fact=off, Stickers=1, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=100%, Fun fact=off, Stickers=1, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=100%, Fun fact=off, Stickers=1, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=100%, Fun fact=off, Stickers=2, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=100%, Fun fact=off, Stickers=2, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=100%, Fun fact=off, Stickers=2, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=100%, Fun fact=off, Stickers=3, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=100%, Fun fact=off, Stickers=3, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=100%, Fun fact=off, Stickers=3, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=100%, Fun fact=off, Stickers=4, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=100%, Fun fact=off, Stickers=4, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=100%, Fun fact=off, Stickers=4, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=100%, Fun fact=on, Stickers=0, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=100%, Fun fact=on, Stickers=0, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=100%, Fun fact=on, Stickers=0, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=100%, Fun fact=on, Stickers=1, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=100%, Fun fact=on, Stickers=1, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=100%, Fun fact=on, Stickers=1, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=100%, Fun fact=on, Stickers=2, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=100%, Fun fact=on, Stickers=2, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=100%, Fun fact=on, Stickers=2, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=100%, Fun fact=on, Stickers=3, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=100%, Fun fact=on, Stickers=3, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=100%, Fun fact=on, Stickers=3, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=100%, Fun fact=on, Stickers=4, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=100%, Fun fact=on, Stickers=4, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=100%, Fun fact=on, Stickers=4, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=25%, Fun fact=off, Stickers=0, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=25%, Fun fact=off, Stickers=0, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=25%, Fun fact=off, Stickers=0, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=25%, Fun fact=off, Stickers=1, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=25%, Fun fact=off, Stickers=1, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=25%, Fun fact=off, Stickers=1, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=25%, Fun fact=off, Stickers=2, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=25%, Fun fact=off, Stickers=2, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=25%, Fun fact=off, Stickers=2, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=25%, Fun fact=off, Stickers=3, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=25%, Fun fact=off, Stickers=3, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=25%, Fun fact=off, Stickers=3, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=25%, Fun fact=off, Stickers=4, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=25%, Fun fact=off, Stickers=4, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=25%, Fun fact=off, Stickers=4, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=25%, Fun fact=on, Stickers=0, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=25%, Fun fact=on, Stickers=0, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=25%, Fun fact=on, Stickers=0, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=25%, Fun fact=on, Stickers=1, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=25%, Fun fact=on, Stickers=1, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=25%, Fun fact=on, Stickers=1, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=25%, Fun fact=on, Stickers=2, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=25%, Fun fact=on, Stickers=2, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=25%, Fun fact=on, Stickers=2, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=25%, Fun fact=on, Stickers=3, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=25%, Fun fact=on, Stickers=3, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=25%, Fun fact=on, Stickers=3, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=25%, Fun fact=on, Stickers=4, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=25%, Fun fact=on, Stickers=4, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=25%, Fun fact=on, Stickers=4, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=50%, Fun fact=off, Stickers=0, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=50%, Fun fact=off, Stickers=0, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=50%, Fun fact=off, Stickers=0, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=50%, Fun fact=off, Stickers=1, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=50%, Fun fact=off, Stickers=1, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=50%, Fun fact=off, Stickers=1, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=50%, Fun fact=off, Stickers=2, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=50%, Fun fact=off, Stickers=2, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=50%, Fun fact=off, Stickers=2, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=50%, Fun fact=off, Stickers=3, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=50%, Fun fact=off, Stickers=3, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=50%, Fun fact=off, Stickers=3, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=50%, Fun fact=off, Stickers=4, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=50%, Fun fact=off, Stickers=4, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=50%, Fun fact=off, Stickers=4, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=50%, Fun fact=on, Stickers=0, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=50%, Fun fact=on, Stickers=0, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=50%, Fun fact=on, Stickers=0, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=50%, Fun fact=on, Stickers=1, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=50%, Fun fact=on, Stickers=1, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=50%, Fun fact=on, Stickers=1, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=50%, Fun fact=on, Stickers=2, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=50%, Fun fact=on, Stickers=2, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=50%, Fun fact=on, Stickers=2, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=50%, Fun fact=on, Stickers=3, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=50%, Fun fact=on, Stickers=3, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=50%, Fun fact=on, Stickers=3, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=50%, Fun fact=on, Stickers=4, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=50%, Fun fact=on, Stickers=4, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=50%, Fun fact=on, Stickers=4, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=75%, Fun fact=off, Stickers=0, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=75%, Fun fact=off, Stickers=0, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=75%, Fun fact=off, Stickers=0, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=75%, Fun fact=off, Stickers=1, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=75%, Fun fact=off, Stickers=1, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=75%, Fun fact=off, Stickers=1, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=75%, Fun fact=off, Stickers=2, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=75%, Fun fact=off, Stickers=2, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=75%, Fun fact=off, Stickers=2, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=75%, Fun fact=off, Stickers=3, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=75%, Fun fact=off, Stickers=3, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=75%, Fun fact=off, Stickers=3, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=75%, Fun fact=off, Stickers=4, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=75%, Fun fact=off, Stickers=4, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=75%, Fun fact=off, Stickers=4, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=75%, Fun fact=on, Stickers=0, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=75%, Fun fact=on, Stickers=0, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=75%, Fun fact=on, Stickers=0, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=75%, Fun fact=on, Stickers=1, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=75%, Fun fact=on, Stickers=1, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=75%, Fun fact=on, Stickers=1, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=75%, Fun fact=on, Stickers=2, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=75%, Fun fact=on, Stickers=2, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=75%, Fun fact=on, Stickers=2, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=75%, Fun fact=on, Stickers=3, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=75%, Fun fact=on, Stickers=3, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=75%, Fun fact=on, Stickers=3, Typos=Playfair Display.png",
        "Pointillés=off, Ratio image=75%, Fun fact=on, Stickers=4, Typos=Hansley - Gloria Hellelujah.png",
        "Pointillés=off, Ratio image=75%, Fun fact=on, Stickers=4, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=off, Ratio image=75%, Fun fact=on, Stickers=4, Typos=Playfair Display.png",
        "Pointillés=on, Ratio image=0%, Fun fact=off, Stickers=0, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=0%, Fun fact=off, Stickers=1, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=0%, Fun fact=off, Stickers=2, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=0%, Fun fact=off, Stickers=3, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=0%, Fun fact=off, Stickers=4, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=0%, Fun fact=on, Stickers=0, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=0%, Fun fact=on, Stickers=1, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=0%, Fun fact=on, Stickers=2, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=0%, Fun fact=on, Stickers=3, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=0%, Fun fact=on, Stickers=4, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=100%, Fun fact=off, Stickers=0, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=100%, Fun fact=off, Stickers=1, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=100%, Fun fact=off, Stickers=2, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=100%, Fun fact=off, Stickers=3, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=100%, Fun fact=off, Stickers=4, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=100%, Fun fact=on, Stickers=0, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=100%, Fun fact=on, Stickers=1, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=100%, Fun fact=on, Stickers=2, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=100%, Fun fact=on, Stickers=3, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=100%, Fun fact=on, Stickers=4, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=25%, Fun fact=off, Stickers=0, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=25%, Fun fact=off, Stickers=1, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=25%, Fun fact=off, Stickers=2, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=25%, Fun fact=off, Stickers=3, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=25%, Fun fact=off, Stickers=4, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=25%, Fun fact=on, Stickers=0, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=25%, Fun fact=on, Stickers=1, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=25%, Fun fact=on, Stickers=2, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=25%, Fun fact=on, Stickers=3, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=25%, Fun fact=on, Stickers=4, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=50%, Fun fact=off, Stickers=0, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=50%, Fun fact=off, Stickers=1, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=50%, Fun fact=off, Stickers=2, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=50%, Fun fact=off, Stickers=3, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=50%, Fun fact=off, Stickers=4, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=50%, Fun fact=on, Stickers=0, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=50%, Fun fact=on, Stickers=1, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=50%, Fun fact=on, Stickers=2, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=50%, Fun fact=on, Stickers=3, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=50%, Fun fact=on, Stickers=4, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=75%, Fun fact=off, Stickers=0, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=75%, Fun fact=off, Stickers=1, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=75%, Fun fact=off, Stickers=2, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=75%, Fun fact=off, Stickers=3, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=75%, Fun fact=off, Stickers=4, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=75%, Fun fact=on, Stickers=0, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=75%, Fun fact=on, Stickers=1, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=75%, Fun fact=on, Stickers=2, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=75%, Fun fact=on, Stickers=3, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
        "Pointillés=on, Ratio image=75%, Fun fact=on, Stickers=4, Typos=Playfair Display - Hansley - Gloria Hallelujah.png",
    ]
}
